### ISSUE TITLE
Import data (Fuelly)

### ISSUE THREAD

**Issue by tiemonl** [akhilrex/hammond#11]
Fuelly currently supports exporting data as a CSV, would it be possible to have an import functionality? I would love to transition to using this instead of Fuelly.

**Comment by akhilrex** [comment]
Can you please attach an exported CSV file which I can study and take
forward. You can replace all the identifying information with dummy data.
Having Real world historical data would really speed up the process.

Thanks and Regards

Akhil Gupta

**Comment by tiemonl** [comment]
I can do that, I'll get around to it later today and send it your way.

**Comment by tiemonl** [comment]
[Fuelly Export.csv](https://github.com/akhilrex/hammond/files/6578234/Fuelly.Export.csv)

Here's an export, I don't have that much data in there as I haven't used all the features. Hopefully someone else could provide another export if they have more data than I can provide

**Comment by poisonthescene** [comment]
[Fuelly Export 2.csv](https://github.com/akhilrex/hammond/files/6642924/Fuelly.Export.2.csv)

I'll also provide an export in case you need more to work with. About a year and a half of data.

**Comment by kavemang** [comment]
I have a dataset from mid 2014 to now which includes the time the android app was called "acar" from before the merge with fuelly, let me know if another set would help, going to try migrating to this as soon as csv import is possible

**Comment by akhilrex** [comment]
This has been done. Just rebuild the container with the latest image and it should be available to you.

**Comment by kavemang** [comment]
sorry to bother about this, is there a guide on proper format to be used in each field? I'm having an issue with the vehicle not being identified/matched even though I have it with the same nickname on Hammond and also am not able to get the date/time of entry to work due to a format error

**Comment by akhilrex** [comment]
Can you share a few rows from the CSV that are giving an issue? Make sure
you copy them using a text editor and not excel.

Thanks and Regards

Akhil Gupta

**Comment by kavemang** [comment]
```
car_name, model, l/100km,  odometer, km, litres, price, city_percentage, fuelup_date, date_added, tags, notes, missed_fuelup, partial_fuelup, latitude, longitude, brand
**Renegade**,Jeep,18.71,186886,306.998,57.432,1.269,50,06/06/2021 **0:00,06/06/2021**,,,0,0,,,
Renegade,Jeep,22.46,186579,248,55.695,1.279,50,04/25/2021 0:00,04/25/2021,,,0,0,,,
Renegade,Jeep,22.31,186331,270,60.245,1.159,100,03/30/2021 0:00,03/30/2021,,,0,0,,,
Renegade,Jeep,23.72,186061,219.997,52.186,1.159,50,03/03/2021 0:00,03/03/2021,,,0,0,,,
Renegade,Jeep,28.65,185841,177.993,51.001,1.049,50,02/13/2021 0:00,02/13/2021,,,0,0,,,
```

I have bolded what I think are the issue columns

**Comment by kavemang** [comment]
For the vehicle I have added in hammond I do not yet have any entries but the nickname field is definitely "Renegade" with no ending or leading blanks on either side

**Comment by jcgoette** [comment]
I think the issue is there are two different ways to export data from Fuelly and they seem to be in different formats.

The way built into Hammond currently is from aCar app, but there is also https://www.fuelly.com/index.php/car/<make>/<model>/<year>/<username>/<id>/export/fuelups.

**Comment by kavemang** [comment]
I think the acar app requires premium to export directly from within the app, ironically I had the pro version before they merged with fuelly and was never able to fix my version back to pro

**Comment by VeganBiker** [comment]
Looks like they only work for acar exports not fuelly exports
