### ISSUE TITLE
Allow for 3 decimals in both fill and price quantity 

### ISSUE THREAD

**Issue by salguero51** [akhilrex/hammond#12]
I would like to request the ability to use 3 (or maybe more?) decimals in both fill and price quantity, as usually both quantity and price uses more decimals at gas stations.

![hammondticket (Small)](https://user-images.githubusercontent.com/4391253/120205226-0009f680-c22a-11eb-94ac-7d93dab765a2.png)

**Comment by EddieFAF** [comment]
I second this request. I guess all stations in Europe, atleast in those countries that have euro as currency, are using prices with 3 decimals.

**Comment by bacco007** [comment]
I support this request - Australia use three decimals too

**Comment by akhilrex** [comment]
This has been done. Please rebuild your container with the latest image once the current build is complete.
