### ISSUE TITLE
Is work on this project continuing?

### ISSUE THREAD

**Issue by jonathanathe** [akhilrex/hammond#127]
Hello to all,

Like many of you, I love this project since I integrated it in my home in October 2021. 

What I see is that it has not been updated for quite some time now, even when there are requests that in my opinion should be repaired, such as the issue of controlling users and so on. I understand that adding improvements is another matter.

If this project is not working already, is there any other project similar to this one that is working and updating that you know of.

Thank you. regards!

**Comment by djjudas21** [comment]
This fork is abandoned, but @AlfHou has a maintained fork: https://github.com/AlfHou/hammond

**Comment by jonathanathe** [comment]
Thank you very much for your help!
