### ISSUE TITLE
Support disabling user authentication

### ISSUE THREAD

**Issue by beauwest** [akhilrex/hammond#15]
I run all of my self-hosted containers behind a reverse proxy with my own authentication. It becomes extra steps if I have to log in through my OAUTH as well as the Hammond authentication.

Cool project, can't wait to see where it goes!

**Comment by akhilrex** [comment]
The auth exists solely to provide multi-user support. If I kill auth then I am not sure how multi-user support would work.

**Comment by beauwest** [comment]
That's fair! In my case I don't need multi-user support, but my situation may not be typical.

**Comment by pascaliske** [comment]
Hi, I have a similar setup as @beauwest. https://github.com/traefik/traefik as a reverse proxy and https://github.com/authelia/authelia as auth platform. It would be really useful if I can either disable auth or use some kind of auth forwarding from the proxy to the service...

**Comment by samcro1967** [comment]
Something I am also interested.  I do not need multi user support and have auth handled by my reverse proxy.

**Comment by spammads** [comment]
Same here. Auth-Header or something would be nice.
