### ISSUE TITLE
After importing form Clarkson, you cannot change imported accounts' passwords

### ISSUE THREAD

**Issue by mrkirby153** [akhilrex/hammond#16]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: [Docker/Native] Docker
 - Have you tried using the latest docker image / code base [yes/no] Yes

**Describe the bug**
After importing from Clarkson, attempting to change an imported account's password from the default ("hammond"), to anything else will result in `Request failed with status code: 422`

**To Reproduce**
1. Import an account from Clarkson
2. Log into the account with the default password: "hammond"
3. Attempt to change the password

**Expected behavior**
The password is changed

**Additional context**
The web request error:
`{"errors":{"OldPassword":"{min: 8}"}}`

**Comment by akhilrex** [comment]
It seems to be a password length validation issue. Are you guys trying passwords shorter than 8 digits?

**Comment by mercplus** [comment]
My password was 8 digits, I tried alphanumeric and pure numeric.

**Comment by akhilrex** [comment]
This has been done. Please rebuild your container with the latest image once the current build is complete.
