### ISSUE TITLE
[Feature Request] Bare metal installation guide

### ISSUE THREAD

**Issue by gigabit942007** [akhilrex/hammond#17]
Please add a guide to install it on a barebones installation.

**Comment by akhilrex** [comment]
Hi

You can find the instructions here - https://github.com/akhilrex/hammond/blob/master/docs/ubuntu-install.md

I did not have a ubuntu machine at hand so I have not been able to test these but the installation steps for the server are the same as those for Podgrab, it should work without any issues (that's tested). The only new thing is building the UI.

If you find any mistake in this, please let me know and I will update the docs.
