### ISSUE TITLE
Cant Remove a Vehicle/Easy to Create Duplicates

### ISSUE THREAD

**Issue by jonootto** [akhilrex/hammond#2]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: [Docker]
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**
When one creates a new vehicle, it's possible to press the submit button twice, creating duplicate entries - there's no obvious way to delete it.
**To Reproduce**
Create vehicle
Click submit twice
Cant delete duplicate entry

**Expected behavior**
Clicking submit should immediately redirect/grey out button
Vehicles should be deleteable

**Screenshots**

**Additional context**

**Comment by mokshmridul** [comment]
Just wanted to add that even non-duplicate entries cannot be deleted.

**Comment by akhilrex** [comment]
Deletion as a functionality is in dev. Will release in a couple of days.

Code was already there to avoid multiple clicks which seemed to have a bug. Its fixed now. For now you can rename the extra entities to something as "To Delete" and delete them once I make the functionality live.

**Comment by akhilrex** [comment]
This has been done. Please rebuild your container with the latest image once the current build is complete.
