### ISSUE TITLE
422 error when logging in

### ISSUE THREAD

**Issue by leon1995** [akhilrex/hammond#23]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: [Docker]
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**
When logging in, it results in a 422 error and I cant log in.

**To Reproduce**
1. Go to login page
2. Enter credentials
3. Click on log in

**Expected behavior**
That I can log in

**Screenshots**
![image](https://user-images.githubusercontent.com/15685899/120885055-11b31b80-c5e7-11eb-86ff-bb7caa418664.jpeg)

Error from the console:
hammond       | [GIN] 2021/06/05 - 08:00:00 | 422 |     375.955µs |  -myIp- | POST     "/api/login"

**Additional context**
Is there a way to reset the password from the commandline?

**Comment by akhilrex** [comment]
Is your password shorter than 6 characters?

**Comment by akhilrex** [comment]
I have made a change in the application. Please rebuild with the latest image and let me know if the issue still persists.

**Comment by leon1995** [comment]
My password has a length of 100 chars (auto generated). I were able to login before. I pulled the newest docker image and tried again. I noticed the following:
Logging in via a desktop pc works, but using a mobile phone does not. I resetted my password to one with 30 chars length, still dont works on mobile...

**Comment by akhilrex** [comment]
Still getting 422?

**Comment by leon1995** [comment]
I did got the error on the web page, but it is not showing up in the container logs. However, I was able to solve the problem. I don't know why, but when I use 1password to import my credentials into the webpage, its not working and I get the error shown above. However, when I copy the password and manually paste it, then its working... I am able to replicate this strange behavior on different devices (phone and tablet).

**Comment by akhilrex** [comment]
I am not sure how I will even replicate this issue. The only way could be if you shared your database file. You think you can do that?

**Comment by leon1995** [comment]
Yes, if you tell me how I can do it? I would like to only share it with you and not the public

**Comment by akhilrex** [comment]
My Gmail is same as my GitHub username.

Thanks and Regards

Akhil Gupta

**Comment by leon1995** [comment]
I cant find the email you mentioned.

**Comment by akhilrex** [comment]
***@***.***

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
[my github username]@ gmail dot com

**Comment by leon1995** [comment]
I just checked, but I cannot send you the database because of data protection :)
