### ISSUE TITLE
Weekdays incorrect on calendar

### ISSUE THREAD

**Issue by jonootto** [akhilrex/hammond#3]
**Please complete the following information**
 - Installation Type: [Docker]
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**
On the calendar, the weekdays are offset by a day. 31 May is a Monday, not a Sunday as per screenshot:

**Screenshots**
<img width="336" alt="image" src="https://user-images.githubusercontent.com/1871850/120162240-4b350100-c24c-11eb-9911-fa73af0f473e.png">

**Comment by akhilrex** [comment]
This is weird!! And outright wrong! It can't even be a timezone isse.

Let me look into this.
