### ISSUE TITLE
Free maintenance intervention

### ISSUE THREAD

**Issue by alegiovannelli** [akhilrex/hammond#38]
I have entered an intervention in the garage under warranty (therefore free of charge) only for the purpose of having a trace.

The application does not allow you to enter an expense with an amount equal to 0 (error 422).

How to solve?

**Comment by akhilrex** [comment]
I have allowed for 0 to be a valid amount value. Please recreate your container once the new image is built.

**Comment by alegiovannelli** [comment]
Thanks for the quick intervention. 

Now if I insert a new expense by putting 0 as the amount everything works regularly, if I go to modify previously entered items the update of the expense to 0 is not saved (no error is generated).

Thanks in advance.
