### ISSUE TITLE
Password Cannot be only numeric

### ISSUE THREAD

**Issue by mokshmridul** [akhilrex/hammond#4]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: Yes

**Describe the bug**
User cannot set an only numeric password such as "123456". It simply fails with error code 422 and no description of the reason for user creation. 

**Expected behavior**
The user should be told that only numeric passwords are not permitted.

**Comment by akhilrex** [comment]
Hi

I don't think it is a numeric only issue. It is most likely a length issue where it requires the password to be minimum of 8 digits long. 

I will add proper messaging there.
