### ISSUE TITLE
Fillups should be sorted on odometer reading

### ISSUE THREAD

**Issue by nicolemon** [akhilrex/hammond#44]
When entering multiple fillups on a single day, they appear to be sorted by on quantity and not odometer reading. As a result, the graph shows some negative MPG numbers for me.

<img width="905" alt="Screen Shot 2021-11-15 at 1 53 29 AM" src="https://user-images.githubusercontent.com/3846455/141760806-e4f3b309-ab5b-4842-b32a-f21cd16105a7.png">

<img width="1304" alt="Screen Shot 2021-11-15 at 1 53 52 AM" src="https://user-images.githubusercontent.com/3846455/141760815-76283115-2d16-41e0-9637-7d54ef6ea059.png">

**Comment by drippyer** [comment]
It seems like this is still the case unfortunately.
![image](https://user-images.githubusercontent.com/6970779/210279019-2c436113-e6a8-4368-b4bd-1270d06cb344.png)
