### ISSUE TITLE
More than 3 vehicles don't fit inside page

### ISSUE THREAD

**Issue by salguero51** [akhilrex/hammond#5]
**Please complete the following information**
 - Installation Type: [Docker]
 - Have you tried using the latest docker image / code base [yes]

**Describe the bug**

If you have more than 3 vehicles, in the main page (Desktop) vehicles are only shown in one row, not creating aditional rows.

**To Reproduce**
1. Add more than 3 vehicles
2. Aditional vehicles are in same row

**Screenshots**

![Screenshot_Hammond](https://user-images.githubusercontent.com/4391253/120166190-a0492680-c1fc-11eb-9554-87c0cb77f209.png)

**Comment by akhilrex** [comment]
Oops!! I have fixed this and have pushed the code. Let it build the container and they you can try with the latest one.
