### ISSUE TITLE
Little Typo

### ISSUE THREAD

**Issue by tpmodding** [akhilrex/hammond#6]
Shreenshots.md should be Screenshots.md, little typo :-)

**Comment by akhilrex** [comment]
I let this one slide out of laziness. Will fix this :)

**Comment by ChrisCarini** [comment]
@akhilrex - I just opened #14 to fix this.

**Comment by tpmodding** [comment]
did not wanted to make a PR only for this :D

**Comment by akhilrex** [comment]
This has been fixed. @ChrisCarini Sorry! Had fixed it already. Just had to push it.
