### ISSUE TITLE
Default User

### ISSUE THREAD

**Issue by xDGmz** [akhilrex/hammond#68]
When setting up with Docker, is there a default user/password already set up? I was not able to locate anything

EDIT: for the evaluation version so I can test it out before actually deploying on my other server

**Comment by djjudas21** [comment]
Looks like all of the issues and PRs are being ignored :disappointed: 

On first run, it should prompt you to create an admin user and then it will save this user/password to the database. If you've been playing with Hammond on Docker you may need to trash the volumes and start afresh.

**Comment by xDGmz** [comment]
Thank you! I gave it a restart "a few" times and thats what helped!

**Comment by umer936** [comment]
For me I actually just needed to refresh the browser page after a few minutes. I think it just takes a bit on first startup.
