### ISSUE TITLE
[BUG] Cant Upload a large file

### ISSUE THREAD

**Issue by mokshmridul** [akhilrex/hammond#93]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: Latest Docker Image

**Describe the bug**
I am unable to upload the attached file to Hammond. It fails will the following error in chrome logs

Chrome Logs:
````
POST http://192.168.0.11:8991/api/vehicles/4e398eb1-922e-4898-ae54-613bf9db8e86/attachments net::ERR_CONNECTION_RESET
````

Docker Container Logs
````
today at 11:05:20 PM[GIN] 2022/05/20 - 17:35:20 | 200 |    1.133269ms |    192.168.0.23 | GET      "/api/vehicles/4e398eb1-922e-4898-ae54-613bf9db8e86/mileage?since=2022-04-20T17:35:22.595Z"
today at 11:05:22 PM[GIN] 2022/05/20 - 17:35:22 | 200 |      324.72µs |      172.18.0.1 | GET      "/"
````

**Expected behavior**
The file should get uploaded.

[Skoda Octavia A8 Manual.pdf](https://github.com/akhilrex/hammond/files/8742386/Skoda.Octavia.A8.Manual.pdf)

**Comment by mokshmridul** [comment]
@akhilrex sorry for the tag, but just wanted to check if this project should be considered closed?

**Comment by motermouth15** [comment]
I am also experiencing this same issue. Has there been any movement here?

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by Brantlab** [comment]
Having the same issue. Trying to upload from IOS and with a photo of 562 KB I wouldn't think I would get this but same general issue. Can't upload photos.
