### ISSUE TITLE
Feature request: Shared/family vehicles

### ISSUE THREAD

**Issue by Back-Man** [akhilrex/hammond#94]
I'm trying to use Hammond to track my family's two cars. I have set up myself as Admin and my wife as a user and created the two cars while logged in as Admin. We each incur expenses for each car. 
There doesn't seem to be a way for my wife to record her expenses without creating duplicate vehicles linked to her account, but that mucks up the mileage calculations if I filled up last time and my wife then fills the car this time.
As a feature request, please create a way to link multiple users to a single car?

**Comment by akhilrex** [comment]
Have you tried the "Share" functionality on the Vehicle detail page? I think that fulfills your requirement.
